version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: proppilot-postgres
    environment:
      - POSTGRES_DB=proppilot
      - POSTGRES_USER=proppilot
      - POSTGRES_PASSWORD=proppilot123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
